# Instala a aplicação

steps:
  # Demonstrate using the maven image directly.
  - name: 'maven'
    id: 'install'
    args: ['mvn', 'clean', 'install']
  - name: 'docker'
    id: 'docker build'
    args: ['build', '-t', 'luanafn/avas-denuncia-backend:$SHORT_SHA', '.']
  - name: 'docker'
    id: login
    args:
      - 'login'
      - '--username=${_DOCKERHUB_LOGIN}'
      - '--password=${_DOCKERHUB_PASS}'
  - name: 'docker'
    id: Push
    args:
      - 'push'
      - 'luanafn/avas-denuncia-backend:$SHORT_SHA'
  - name: 'gcr.io/cloud-builders/kubectl'
    id: kubecongif
    args:
      - 'create'
      - 'deployment'
      - 'demo'
      - '--image=luanafn/avas-denuncia-backend'
      - '--dry-run'
      - '-o=yaml'
      - '>kubernetes.yaml'
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    args:
      - 'apply'
      - '-f'
      - 'kubernetes.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=southamerica-east1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=denuncia-backend'