# Instala a aplicação

steps:
  - name: 'docker'
    id: 'docker build'
    args: ['build', '--build-arg', 'branch=$BRANCH_NAME', '-t', 'luanafn/avas-denuncia-backend:latest', '.']
  - name: 'docker'
    id: login
    args:
      - 'login'
      - '--username=${_DOCKERHUB_LOGIN}'
      - '--password=${_DOCKERHUB_PASS}'
  - name: 'docker'
    id: Push
    args:
      - 'push'
      - 'luanafn/avas-denuncia-backend:latest'
  - name: 'docker'
    id: PullTest
    args:
      - 'pull'
      - 'luanafn/avas-denuncia-backend'
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    args:
      - 'apply'
      - '-f'
      - 'kubernetes.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=southamerica-east1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=denuncia-backend'