# Instala a aplicação

steps:
  - name: 'docker'
    id: PullTest
    args:
      - 'pull'
      - 'docker.pkg.github.com/luanafn/avas-denuncia-backend'
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    args:
      - 'apply'
      - '-f'
      - 'kubernetes.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=southamerica-east1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=denuncia-backend'