# Instala a aplicação

steps:
  # Demonstrate using the maven image directly.
  - name: 'maven'
    id: 'clean'
    args: ['mvn', 'clean']
  - name: 'maven'
    id: 'test'
    args: ['mvn', 'test']
  - name: 'maven'
    id: 'install'
    args: ['mvn', 'install']
  - name: 'docker'
    id: 'docker build'
    args: ['build', 'Dockerfile']
  - name: 'docker'
    id: 'docker run'
    args: ['run']