apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dep-dev
  name: dep-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep-dev
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dep-dev
    spec:
      containers:
      - image: luanafn/avas-denuncia-backend
        name: avas-denuncia-backend
        resources: {}
status: {}
