# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Dev env

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Install
        run: mvn clean install

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Secret Scan
        uses: max/secret-scan@1.0.0

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: rlespinasse/github-slug-action@master
      - name: Print slug variables
        run: |
          echo ${{ env.GITHUB_REF_SLUG }}
          echo ${{ env.GITHUB_HEAD_REF_SLUG }}
          echo ${{ env.GITHUB_BASE_REF_SLUG }}
          echo ${{ env.GITHUB_SHA_SHORT }}

      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: luanafn/avas-denuncia-backend
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          buildargs: branch=${{ env.GITHUB_REF_SLUG }}

      - name: Deploy on heroku
        uses: akhileshns/heroku-deploy@v3.0.2 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "avas-denuncia-backend"
          heroku_email: "lluana13@hotmail.com"
          buildpack: heroku/java