name: Create Release

on:
  pull_request:
    types: closed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica PR
        uses: "tayfun/flake8-your-pr@master"
        secrets: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out code.
        uses: actions/checkout@v1
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "BR"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}